### PR TITLE
Fixed adjacency block problems, 2D grid generation and added tree layout toggle

### LINKED ISSUE #225: generate 2D grid graph block doesn't work
This block reports a reference error (G is not defined).

### LINKED ISSUE #226: set adj to 0
When a edge is deleted in the adjacency-matrix representation, there is no requirement that it exist already. I.e. "set adj x y to 0" should work even if there does not yet exist an edge from x to y.

### LINKED ISSUE #227: set adj attr to x
Currently this is forced to be an integer. However, it can be a string, e.g. when the attribute is a color.

### PR DESCRIPTION
**Pull request by jarredgallina**
I think that the way the adjacency functions are called might have changed at some point, because there were inconsistencies in their bodies that were causing errors. I've mad small changes to fix these issues, and done a bit of testing to make sure I haven't ruined everything. As far as I can tell all four of these blocks now work as intended. This resolves #226 and resolves #227. 

The 2D generator now works. Resolves #225 

I've added a tree layout button, but the layout itself doesn't display anything yet. 
(I couldn't figure out how to make a pull request without including this, sorry)

EDIT: Also changed a miscalled variable that stopped nodes from being renamed in a digraph.

### CODE REVIEW

**Comment by stevenbird** [comment]
I think we can resolve this by getting this block to require a numerical value:
set_adj1
(The parameter can only be interpreted as the value of the cell in the adjacency matrix.)

And getting this block to require a non-empty value in the drop-down menu:
set_adj2
(The parameter can never be interpreted as the value of the cell in the adjacency matrix.)

**Comment by Muon** [comment]
I'm a bit confused as to what the problem is here. What's the second block type supposed to solve?

**Comment by stevenbird** [comment]
The second block type permits edge attributes to be set.

@jarredgallina would you please go ahead with the extra constraints I proposed above, then I can merge this, thanks.

**Comment by jarredgallina** [comment]
I made those changes but I still don't think we're all on the same page with this. Perhaps you should merge it for now and then we can discuss it further elsewhere?

**Pull request merged**
